# Change baseurl before deploy
baseurl      = "https://liu-houliang.github.io/hugo-stack-starter/"
languageCode = "zh-cn"
title        = "Hugo Theme Stack Starter Template"

# Set default language
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = true

[pagination]
    pagerSize = 10
