[zh]
    languageCode      = "zh-cn"
    languageName      = "中文"
    languagedirection = "ltr"
    title             = "我的博客"
    weight            = 1

[en]
    languageCode      = "en-us"
    languageName      = "English"
    languagedirection = "ltr"
    title             = "My Blog"
    weight            = 2
